server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1337
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

# example values

indexing-settings:
  sites:
        - url: https://nikoartgallery.com
          name: Галерея искусств Niko
#
        - url: https://ipfran.ru/
          name: ИПФ РАН
#
#      #520 + a lot of errors
#          #169
#
#        - url:  http://playback.ru/
#          name: playback.ru
##       4225 и завис
#
#        - url: https://volochek.life/
#          name: volochek.life
#          #4k+ full memory
#
##        - url: https://radiomv.ru/
##          name: radiomv.ru
#  #0
#
#
#
#
#
#        - url:  https://dimonvideo.ru/
#          name: dimonvideo.ru
#          #   260+ 30k lemmas
#
#
#
#        - url:  https://et-cetera.ru/mobile/
#          name: et-cetera.ru
#  #ochen dolgo hz
#
#        - url: https://dombulgakova.ru/
#          name: dombulgakova.ru
#        #1300+ a lot of erros and memory use
#
#
#
#
#        - url: https://www.svetlovka.ru/
#          name: svetlovka.ru
##      2000+ завис







