server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1337
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

# example values

indexing-settings:
  sites:
        - url: https://nikoartgallery.com
          name: Галерея искусств Niko
#
#        - url: https://ipfran.ru/
#          name: ИПФ РАН
#
#        - url:  http://playback.ru/
#          name: playback.ru
#
#        - url: https://volochek.life/
#          name: volochek.life
#
#        - url: https://radiomv.ru/
#          name: radiomv.ru
#
#        - url:  https://dimonvideo.ru/
#          name: dimonvideo.ru
#
#        - url:  https://et-cetera.ru/mobile/
#          name: et-cetera.ru
#
#        - url: https://dombulgakova.ru/
#          name: dombulgakova.ru
#
#        - url: https://www.svetlovka.ru/
#          name: svetlovka.ru







